### ISSUE TITLE
Error reloading exercise page

### ISSUE THREAD

**Issue by ango1994** [JdeRobot/RoboticsApplicationManager#106]
An X11 connection breaks and I think the gazebo client dies, forcing the container to restart.

![unibotics_bug_docker_f5](https://github.com/JdeRobot/RoboticsApplicationManager/assets/81623139/0751b906-e41f-4abd-8feb-cebecdbcdc2a)
![unibotics_bug_docker_f5_web](https://github.com/JdeRobot/RoboticsApplicationManager/assets/81623139/3999ee99-e587-4738-8924-f7ebb18cae9a)

**Comment by OscarMrZ** [comment]
Solved in the last versions of the manager.
