### ISSUE TITLE
Add requirements.txt for Dependency Management

### ISSUE THREAD

**Issue by Surajpatra700** [JdeRobot/RoboticsApplicationManager#117]
This issue is created to address the need for a requirements.txt file in the repository. The absence of this file currently makes it challenging for users to easily install the required dependencies for the framework. By adding a requirements.txt file, we ensure a smoother onboarding process for contributors and users who want to explore and utilize the features provided by the framework.

**Comment by BkPankaj** [comment]
Hi @Surajpatra700 ,
Thank you for addressing this issue; it will be truly helpful. However, I am encountering difficulties in setting up the environment following the provided README. If I understand correctly, you mentioned the requirements.txt in the README for installation. Could you kindly guide me through the installation process? I am encountering errors as shown in the below image when attempting to install individual libraries. Your assistance would be greatly appreciated.
![](https://github.com/JdeRobot/RoboticsApplicationManager/assets/62588059/b5b5858d-0eb9-4087-847c-34fb4476978f)

**Comment by BkPankaj** [comment]
Hello @Surajpatra700 ,
Thank you for bringing up this issue; it's truly essential. I'm currently following the installation steps outlined in the README, but I'm encountering errors. I've tried installing individual libraries, yet I consistently encounter the following error:

Terminal error about src
![](https://github.com/JdeRobot/RoboticsApplicationManager/assets/62588059/6c3da830-8446-4053-87d1-3d3f188e78e0)

Inside code
![Screenshot from 2024-02-03 20-01-59](https://github.com/JdeRobot/RoboticsApplicationManager/assets/62588059/ea4b31b0-fe36-40d6-98d3-04837c5620a8)


Could you please guide me through setting up RAM on my local machine by providing any relevant documentation?

**Comment by OscarMrZ** [comment]
Currently, the manager is intended to be run inside a docker RADI image. This could be a good step to allow native execution. Please check the dockerfiles at RoboticsAcademy to get a good idea of the dependencies.

**Comment by BkPankaj** [comment]
Hey @OscarMrZ , Are you referring to [this](https://github.com/JdeRobot/RoboticsAcademy/blob/master/docs/requirements.txt)? Could you provide more information on how to obtain RAM dependencies from the Dockerfiles of RoboticsAcademy?

**Comment by espilya** [comment]
To get the RADI (Now RB) dependencies, you can open the `scripts/mini_RADI/Dockerfile.dependencies_humble` Dockerfile and search for `# pip install dependencies` line.
And if you want only RAM dependencies, then you have `requirements.txt`.
