### ISSUE TITLE
Add exercise_wrapper avaliable with teleoperable person

### ISSUE THREAD

**Issue by Blancasr** [JdeRobot/RoboticsApplicationManager#30]

**Comment by OscarMrZ** [comment]
In the new manager, the exercise can use the gui_broker started by the manager to communicate with the browser, so I think no exercise wrapper is needed.

**Comment by jmplaza** [comment]
Yes, the teleoperation will performed with the GUI.py receiving the pressed keys from the browser through the regular websocket connecting the RAM (and the gui-broker) and the browser. This way no extra port will be required and the functionality is solved in the python template, not in the manager.
The corresponding issue is https://github.com/JdeRobot/RoboticsAcademy/issues/2415
